
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.WindowConstants;
import javax.swing.JOptionPane;
import java.io.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author himel9675
 */
public class UnitsBoard extends javax.swing.JFrame {
    public static final int height =6;
    public static final int width =6;
    public static final String[][] Question=new String[height][width];
    public static final String[][] Answer=new String[height][width];
    /**
     * Creates new form UnitsBoard
     */
    public UnitsBoard() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Question1 = new javax.swing.JButton();
        Question2 = new javax.swing.JButton();
        Question3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Question1.setText("1 ");
        Question1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Question1ActionPerformed(evt);
            }
        });

        Question2.setText("2 ");
        Question2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Question2ActionPerformed(evt);
            }
        });

        Question3.setText("3");
        Question3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Question3ActionPerformed(evt);
            }
        });

        jButton4.setText("4 ");

        jButton1.setText("5 ");

        jButton5.setText("6");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton4)
                    .addComponent(Question3)
                    .addComponent(Question2)
                    .addComponent(Question1)
                    .addComponent(jButton5))
                .addContainerGap(611, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(Question1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Question2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Question3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(326, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        //exit
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    
    private void Question1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Question1ActionPerformed
        
        String test1;
        test1 = JOptionPane.showInputDialog(Question[1][1]);
        System.out.println(test1+"Replication");
        if (test1 == Answer[1][1]){
            JOptionPane.showMessageDialog(null,Answer[1][1] );
        }
        else
        {JOptionPane.showMessageDialog(null,Answer[1][1] +"No" );}
        JButton source = (JButton) evt.getSource();
        source.setEnabled(false);
        source.setBackground(Color.GREEN);
        System.out.println(Answer[1][1] );
    }//GEN-LAST:event_Question1ActionPerformed

    
    
    private void Question3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Question3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Question3ActionPerformed

    private void Question2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Question2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Question2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String test1;
        test1 = JOptionPane.showInputDialog(Question[1][1]);
        System.out.println(test1+"Replication");
        if (test1 == Answer[1][1]){
            JOptionPane.showMessageDialog(null,Answer[1][1] );
        }
        else
        {JOptionPane.showMessageDialog(null,Answer[1][1] +"No" );}
        JButton source = (JButton) evt.getSource();
        source.setEnabled(false);
        source.setBackground(Color.GREEN);
        System.out.println(Answer[1][1] );    }//GEN-LAST:event_jButton5ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main() throws IOException{
        
        System.out.println("subframe1");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UnitsBoard().setVisible(true);
            }
        });
        System.out.println("subframe2");
        int l,m,n;
        String Qestio,Answe,Section;
        String[] Chapter = {"Cells","Genetics","Circulation & Digestion & Respiration","Plants","Diversity of living things", "Evolution" };
        String f1="/home/sdx/NetBeansProjects/Game/src/QuestionAnswer.txt";
        BufferedReader reader = new BufferedReader(new FileReader(f1));
//        ArrayList<String> lines = new ArrayList<String>();
String s;
String S;
S="";
//        String[][] Question=new String[height][width];
//        String[][] Answer=new String[height][width];
while ((s = reader.readLine()) != null) {
    S=S+s;
}
reader.close();

for ( int i = 0; i < height; i++) {
    l=S.indexOf(Chapter[i]);
    if(i<5)
    {
        m=S.indexOf(Chapter[i+1]);
        Section=S.substring(l,m);
    }
    else
    {
        Section=S.substring(l,S.length());
    }
    for (int  j = 0; j < width; j++) {
        l=Section.indexOf(String.valueOf(j+1)+". ");
        m=Section.indexOf("a. ",1);
        Qestio=Section.substring(l+3, m);
        Question[i][j]=Qestio;
        Section=Section.substring(m,Section.length());
        
        n=Section.indexOf("()",1);
        Answe=Section.substring(2,n);
        Answer[i][j]=Answe;
        System.out.println(Answe);
    }
}

    }
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Question1;
    private javax.swing.JButton Question2;
    private javax.swing.JButton Question3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
